name: Publish to Docker Hub

on:
    push:
        branches:
            - master
            - "actions/docker-publish"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Publish to Registry
              uses: elgohr/Publish-Docker-Github-Action@master
              with:
                  name: krubenok/quill
                  username: ${{ secrets.DOCKER_USER }}
                  password: ${{ secrets.DOCKER_PASS }}
